export enum GeneralSetting {
  CurrentUser = "CurrentUser",
  CurrentServerConfig = "CurrentServerConfig",
  CurrentLibraryId = "CurrentLibraryId",
  DeviceData = "DeviceData",
  ServerSettings = "ServerSettings",
  TempBookFiles = "TempBookFiles",
  AppTheme = "AppTheme",
  Sort = "Sort",
  DescOrder = "DescOrder",
  EbookSettings = "EbookSettings",
  DeviceId = "DeviceId",
  BookAnnotations = "BookAnnotations",
  LastLibraryId = "LastLibraryId",
  CachedBookFilePaths = "CachedBookFilePaths",
}
